name: DevOps Full CI-CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4


      # Configure AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}


      # ===============================
      # Terraform Infrastructure
      # ===============================
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      - name: Terraform Apply
        working-directory: terraform
        run: terraform apply -auto-approve


      # ===============================
      # Login to Amazon ECR
      # ===============================
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2


      # ===============================
      # Build & Push Backend
      # ===============================
      - name: Build & Push Backend
        run: |
          docker build -t backend ./backend
          docker tag backend:latest ${{ steps.login-ecr.outputs.registry }}/devops-backend:${{ github.sha }}
          docker push ${{ steps.login-ecr.outputs.registry }}/devops-backend:${{ github.sha }}


      # ===============================
      # Build & Push Frontend
      # ===============================
      - name: Build & Push Frontend
        run: |
          docker build -t frontend ./frontend
          docker tag frontend:latest ${{ steps.login-ecr.outputs.registry }}/devops-frontend:${{ github.sha }}
          docker push ${{ steps.login-ecr.outputs.registry }}/devops-frontend:${{ github.sha }}


      # ===============================
      # Get EC2 Public IP
      # ===============================
      - name: Get EC2 Public IP
        working-directory: terraform
        run: |
          echo "EC2_IP=$(terraform output -raw ec2_public_ip)" >> $GITHUB_ENV

      # ===============================
      # Deploy to EC2
      # ===============================
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ env.EC2_IP }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: |

            # Login to ECR
            aws ecr get-login-password --region ${{ secrets.AWS_REGION }} \
            | sudo docker login --username AWS --password-stdin ${{ steps.login-ecr.outputs.registry }}

            # Pull Images
            sudo docker pull ${{ steps.login-ecr.outputs.registry }}/devops-backend:${{ github.sha }}
            sudo docker pull ${{ steps.login-ecr.outputs.registry }}/devops-frontend:${{ github.sha }}

            # Stop Old Containers
            sudo docker stop backend || true
            sudo docker rm backend || true

            sudo docker stop frontend || true
            sudo docker rm frontend || true

            # Run Backend
            sudo docker run -d -p 8000:8000 \
            --name backend \
            ${{ steps.login-ecr.outputs.registry }}/devops-backend:${{ github.sha }}

            # Run Frontend
            sudo docker run -d -p 80:80 \
            --name frontend \
            ${{ steps.login-ecr.outputs.registry }}/devops-frontend:${{ github.sha }}

            # Check 