name: DevOps Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout repository
      uses: actions/checkout@v4


    # Configure AWS credentials
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}


    # Login to Amazon ECR
    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v2


    # Build and push backend
    - name: Build Backend
      run: |
        docker build -t backend ./backend
        docker tag backend:latest ${{ secrets.ECR_BACKEND_REPO }}:${{ github.sha }}
        docker push ${{ secrets.ECR_BACKEND_REPO }}:${{ github.sha }}


    # Build and push frontend
    - name: Build Frontend
      run: |
        docker build -t frontend ./frontend
        docker tag frontend:latest ${{ secrets.ECR_FRONTEND_REPO }}:${{ github.sha }}
        docker push ${{ secrets.ECR_FRONTEND_REPO }}:${{ github.sha }}


    # Setup Terraform
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3


    # Run Terraform
    - name: Terraform Apply
      run: |
        cd terraform
        terraform init
        terraform apply -auto-approve


    # Wait for instance boot
    - name: Wait for EC2 startup
      run: sleep 90


    # Get EC2 public IP dynamically
    - name: Get EC2 Public IP
      run: |
        EC2_IP=$(aws ec2 describe-instances \
          --filters "Name=tag:Name,Values=DevOps-App-Server" "Name=instance-state-name,Values=running" \
          --query "Reservations[].Instances[].PublicIpAddress" \
          --output text | awk '{print $1}')

        echo "EC2_IP=$EC2_IP" >> $GITHUB_ENV
        echo "Using EC2 IP: $EC2_IP"


    # Deploy containers to EC2
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ env.EC2_IP }}
        username: ec2-user
        key: ${{ secrets.EC2_KEY }}
        script: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} \
          | docker login --username AWS --password-stdin $(echo ${{ secrets.ECR_BACKEND_REPO }} | cut -d'/' -f1)

          docker pull ${{ secrets.ECR_BACKEND_REPO }}:${{ github.sha }}
          docker pull ${{ secrets.ECR_FRONTEND_REPO }}:${{ github.sha }}

          docker stop backend || true
          docker stop frontend || true
          docker rm backend || true
          docker rm frontend || true

          docker run -d -p 8000:8000 --name backend ${{ secrets.ECR_BACKEND_REPO }}:${{ github.sha }}
          docker run -d -p 80:80 --name frontend ${{ secrets.ECR_FRONTEND_REPO }}:${{ github.sha }}